# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_aselsan_ui(object):
    def setupUi(self, aselsan_ui):
        aselsan_ui.setObjectName("aselsan_ui")
        aselsan_ui.resize(1247, 858)
        aselsan_ui.setStyleSheet("QWidget {\n"
"  background-color: #00557f;\n"
"  border: 0px solid #32414B;\n"
"  padding: 0px;\n"
"  color: #F0F0F0;\n"
"  selection-background-color: #1464A0;\n"
"  selection-color: #F0F0F0;\n"
"}\n"
"\n"
"QWidget:disabled {\n"
"  background-color: #19232D;\n"
"  color: #787878;\n"
"  selection-background-color: #14506E;\n"
"  selection-color: #787878;\n"
"}\n"
"\n"
"QWidget::item:selected {\n"
"  background-color: #1464A0;\n"
"}\n"
"\n"
"QWidget::item:hover {\n"
"  background-color: #148CD2;\n"
"  color: #32414B;\n"
"}\n"
"")
        self.label_3 = QtWidgets.QLabel(aselsan_ui)
        self.label_3.setGeometry(QtCore.QRect(450, 30, 331, 81))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:\\Users\\kaant\\Desktop\\Heuristic\\src\\inventory\\aselsan_logo.png"))
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(aselsan_ui)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 130, 742, 333))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sure = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.sure.setFont(font)
        self.sure.setObjectName("sure")
        self.gridLayout_2.addWidget(self.sure, 1, 0, 1, 1)
        self.input_sure = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.input_sure.setFont(font)
        self.input_sure.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.input_sure.setObjectName("input_sure")
        self.gridLayout_2.addWidget(self.input_sure, 1, 2, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.parti_suresi = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.parti_suresi.setFont(font)
        self.parti_suresi.setObjectName("parti_suresi")
        self.gridLayout.addWidget(self.parti_suresi, 3, 3, 1, 3)
        self.input_minpartisayisi = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.input_minpartisayisi.setFont(font)
        self.input_minpartisayisi.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.input_minpartisayisi.setObjectName("input_minpartisayisi")
        self.gridLayout.addWidget(self.input_minpartisayisi, 2, 3, 1, 2)
        self.toplam_sure = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.toplam_sure.setFont(font)
        self.toplam_sure.setObjectName("toplam_sure")
        self.gridLayout.addWidget(self.toplam_sure, 4, 3, 1, 3)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 2, 1, 1)
        self.partisayisi = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.partisayisi.setFont(font)
        self.partisayisi.setObjectName("partisayisi")
        self.gridLayout.addWidget(self.partisayisi, 2, 0, 1, 2)
        self.kisisayisi = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.kisisayisi.setFont(font)
        self.kisisayisi.setObjectName("kisisayisi")
        self.gridLayout.addWidget(self.kisisayisi, 0, 0, 1, 2)
        self.input_kisisayisi = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.input_kisisayisi.setFont(font)
        self.input_kisisayisi.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.input_kisisayisi.setObjectName("input_kisisayisi")
        self.gridLayout.addWidget(self.input_kisisayisi, 0, 7, 1, 1)
        self.max_partisayisi = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.max_partisayisi.setFont(font)
        self.max_partisayisi.setObjectName("max_partisayisi")
        self.gridLayout.addWidget(self.max_partisayisi, 2, 5, 1, 2)
        self.input_maxPartiSayisi = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.input_maxPartiSayisi.setFont(font)
        self.input_maxPartiSayisi.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.input_maxPartiSayisi.setObjectName("input_maxPartiSayisi")
        self.gridLayout.addWidget(self.input_maxPartiSayisi, 2, 7, 1, 1)
        self.input_PartiSuresi = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.input_PartiSuresi.setFont(font)
        self.input_PartiSuresi.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.input_PartiSuresi.setObjectName("input_PartiSuresi")
        self.gridLayout.addWidget(self.input_PartiSuresi, 3, 7, 1, 1)
        self.input_toplamSure = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.input_toplamSure.setFont(font)
        self.input_toplamSure.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);")
        self.input_toplamSure.setObjectName("input_toplamSure")
        self.gridLayout.addWidget(self.input_toplamSure, 4, 7, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gozat = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.gozat.setFont(font)
        self.gozat.setObjectName("gozat")
        self.verticalLayout.addWidget(self.gozat)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.iptal = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.iptal.setFont(font)
        self.iptal.setObjectName("iptal")
        self.horizontalLayout.addWidget(self.iptal)
        self.calistir = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.calistir.setFont(font)
        self.calistir.setObjectName("calistir")
        self.horizontalLayout.addWidget(self.calistir)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(aselsan_ui)
        QtCore.QMetaObject.connectSlotsByName(aselsan_ui)

    def retranslateUi(self, aselsan_ui):
        _translate = QtCore.QCoreApplication.translate
        aselsan_ui.setWindowTitle(_translate("aselsan_ui", "Form"))
        self.sure.setText(_translate("aselsan_ui", "Kodun Çalışma Süresi  "))
        self.parti_suresi.setText(_translate("aselsan_ui", "Parti Süresi:"))
        self.toplam_sure.setText(_translate("aselsan_ui", "Toplam Süre:"))
        self.label.setText(_translate("aselsan_ui", "min"))
        self.partisayisi.setText(_translate("aselsan_ui", "Parti Sayısı:"))
        self.kisisayisi.setText(_translate("aselsan_ui", "Kişi Sayısı:"))
        self.max_partisayisi.setText(_translate("aselsan_ui", "max"))
        self.gozat.setText(_translate("aselsan_ui", "Gözat"))
        self.iptal.setText(_translate("aselsan_ui", "İPTAL"))
        self.calistir.setText(_translate("aselsan_ui", "ÇALIŞTIR"))
